INSERT_GOLD = """
INSERT INTO gold.playergame
(
    player_name, 
    player_id, 
    position, 
    height, 
    weight, 
    age,
    draft_year, 
    draft_round, 
    draft_selection, 
    status,
    team_name, 
    team_id,
    game_id, 
    game_slug, 
    season, 
    week,
    home_team_id, 
    away_team_id, 
    home_score, 
    away_score,
    game_date, 
    weather_condition, 
    temperature, 
    wind_speed,
    passing_attempts, 
    passing_completions, 
    passing_yards, 
    passing_tds,
    interceptions, 
    rushing_attempts, 
    rushing_yards, 
    rushing_tds,
    targets, 
    receptions, 
    receiving_yards, 
    receiving_tds,
    fumbles, 
    fumbles_lost,
    home_away, 
    first_downs, 
    third_down_conversions, 
    third_down_attempts,
    fourth_down_conversions, 
    fourth_down_attempts, 
    total_plays, 
    total_yards,
    yards_per_play, 
    total_drives, 
    net_passing_yards,
    team_passing_completions, 
    team_passing_attempts, 
    yards_per_pass,
    interceptions_thrown, 
    sacks, 
    sack_yards_lost,
    team_rushing_yards, 
    team_rushing_attempts, 
    yards_per_rush,
    red_zone_conversions, 
    red_zone_attempts, 
    turnovers,
    team_fumbles_lost, 
    possession_time_seconds
)
SELECT
    p.name                      AS player_name,
    p.espn_id                   AS player_id,
    p.position,
    p.height,
    p.weight,
    p.age,
    p.draft_year,
    p.draft_round,
    p.draft_selection,
    p.status,
 
    t.name                      AS team_name,
    pgs.team_id,
 
    g.espn_id                   AS game_id,
    g.slug                      AS game_slug,
    g.season,
    g.week,
    g.home_team_id,
    g.away_team_id,
    g.home_score,
    g.away_score,
    g.game_date,
    g.weather_condition,
    g.temperature,
    g.wind_speed,
 
    pgs.passing_attempts,
    pgs.passing_completions,
    pgs.passing_yards,
    pgs.passing_tds,
    pgs.interceptions,
    pgs.rushing_attempts,
    pgs.rushing_yards,
    pgs.rushing_tds,
    pgs.targets,
    pgs.receptions,
    pgs.receiving_yards,
    pgs.receiving_tds,
    pgs.fumbles,
    pgs.fumbles_lost,
 
    tgs.home_away,
    tgs.first_downs,
    tgs.third_down_conversions,
    tgs.third_down_attempts,
    tgs.fourth_down_conversions,
    tgs.fourth_down_attempts,
    tgs.total_plays,
    tgs.total_yards,
    tgs.yards_per_play,
    tgs.total_drives,
    tgs.net_passing_yards,
    tgs.passing_completions     AS team_passing_completions,
    tgs.passing_attempts        AS team_passing_attempts,
    tgs.yards_per_pass,
    tgs.interceptions_thrown,
    tgs.sacks,
    tgs.sack_yards_lost,
    tgs.rushing_yards           AS team_rushing_yards,
    tgs.rushing_attempts        AS team_rushing_attempts,
    tgs.yards_per_rush,
    tgs.red_zone_conversions,
    tgs.red_zone_attempts,
    tgs.turnovers,
    tgs.fumbles_lost            AS team_fumbles_lost,
    tgs.possession_time_seconds
 
FROM silver.playergamestats pgs
JOIN silver.players  p   ON p.espn_id  = pgs.player_id
JOIN silver.games    g   ON g.espn_id  = pgs.game_id
JOIN silver.teams    t   ON t.espn_id  = pgs.team_id
JOIN silver.teamgamestats tgs
    ON  tgs.game_id = pgs.game_id
    AND tgs.team_id = pgs.team_id
"""
